# Generated by Django 3.1.7 on 2021-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_app', '0002_post_algorithm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sorted_list',
            field=models.TextField(default=[1]),
        ),
        migrations.AddField(
            model_name='post',
            name='time_to_sort',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
