# Generated by Django 3.1.7 on 2021-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_app', '0003_auto_20210326_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
